### ISSUE TITLE
Pulse reports: Download as CSV

### ISSUE THREAD

**Issue by Dmfama20** [bdecentgmbh/moodle-mod_pulse#12]
Hi,

when I'm inside a course and click "course-administration"->"reports"->"Pulse reports", I see all Pulse messages sent to  students (>400 students in course). 
When I try to download this table as CSV, Excel, etc, the corresponding file only contains 10 students. I got the same result, when I click "Show all 443" first, such that all students are listed on one page.

TIA!
Alex

**Comment by stefanscholz** [comment]
@Dmfama20 this issue should be fixed in the latest version (dev branch).
If you want to test it, download the files from the dev branch and have a look.

**Comment by stefanscholz** [comment]
Fixed in 1.3
