### ISSUE TITLE
inflationary use of course logs

### ISSUE THREAD

**Issue by Dmfama20** [bdecentgmbh/moodle-mod_pulse#13]
Hi,
we have a quite large course containing approximately 350 activities (most of them containing completion criteria) and 450 students. In this course we have two pulse activities.
When I look into the course logs of a single day I find more than 389000 log entries and only ~20000 logs resulting from origin "Web". The major part of the remaining ~370000 logs are produced by the two pulse activities which are something like

_The user with id 'XXXX' updated the completion state for the course module with id 'YYYYY' for the user with id 'ZZZZZ'._

Now, the large number of course logs lead to a crash of the course backup, when the log files are included!

Why do you need to write all changes of activity completions in the logs? Since moodle has own logfiles where activity completions are tracked.

TIA!
Alex

**Comment by stefanscholz** [comment]
Hi Alex,

we have encountered this issue on other sites; we have a newer version of Pulse which is not yet released to the moodle plugin directory, but you can get it here: https://github.com/bdecentgmbh/moodle-mod_pulse/tree/dev 
It comes with a setting to make pulse more silent.
You could try if that helps!

Best
Stefan

**Comment by stefanscholz** [comment]
I just saw that you seem to be a Pulse Pro customer; in this case, you'll need the upgrade for both plugins (mod_pulse and local_pulsepro). Please reach out directly and I'll provide it to you via email/wetransfer. Thanks!
