### ISSUE TITLE
Email sent to wrong parents

### ISSUE THREAD

**Issue by osmanfindik** [bdecentgmbh/moodle-mod_pulse#14]
We have received complaints from some parents that they received emails with incorrect student information. I have emails forwarded to me from parents and checked the LMS system if those students and those parents have anything in common. I personally couldn't find anything but when Pulse Pro is used in a large class we are facing this issue. In small classes or individual test trials I couldn't recreate the issue. 

I can show the error and the emails in a zoom call if needed.

**Comment by stefanscholz** [comment]
Hi Osman, 

sorry for the late reply, and sorry to hear that you are having issues.
A meeting probaly helps, please set one up here: https://calendly.com/bdecent/
Even better would be if you could somehow figure out if there is any logic/rules behind who gets them.
Can you rule out that (at the time of the notification) the students actually had the (right) parents? 

Have you been able to reproduce the issue? That would help a lot.

Best
Stefan

**Comment by osmanfindik** [comment]
Thank you for the reply. I have scheduled a meeting. 

> Can you rule out that (at the time of the notification) the students actually had the (right) parents?

I already checked to see if those students and parents have any relation at LMS at all. And the answer is no. 

> Have you been able to reproduce the issue? That would help a lot.

I was not able to reproduce the issue.
