### ISSUE TITLE
Puls plugin

### ISSUE THREAD

**Issue by Gosiattms** [bdecentgmbh/moodle-mod_pulse#15]
Hello, I have a problem with your Pulse plugin. I've used it to send an invitation massages to all of the users after enrolling them into a particular course. The problem is that the messages never arrived. I've compared the settings of this course with another one in which the notifications worked, but there was no difference both in course settings and Pulse settings. Is there maybe some kind of instruction you could send me that shows how to set this invitation massages correctly?

**Comment by stefanscholz** [comment]
Hi!

the most common issues are the following:
- Course has not started yet (course start date must be in the past)
- Pulse activity is not available (it must be either available or visible, can't be hidden)
- Course is hidden (course and the parent course categories must be visible)
- Student's enrolment is active and uses the student role
- Cron job is running (but that can probably be ruled out if it works for another course on the same site in your case) 

Hope this helps!
Stefan
