### ISSUE TITLE
lib.php is way too big

### ISSUE THREAD

**Issue by abias** [bdecentgmbh/moodle-mod_pulse#16]
Quoting https://docs.moodle.org/dev/Plugin_files#lib.php:

> Moodle core often (but not always) loads all the lib.php files of the given plugin types. For the performance reasons, it is strongly recommended to keep this file as small as possible and have just required code implemented in it.

mod_pulse, unfortunately, does not follow this rule and ships with a bunch of local functions which should be places in locallib.php or - even better - in classes instead.

**Comment by stefanscholz** [comment]
Thanks for reporting this @abias — we'll discuss it internally and improve it in the upcoming release.

**Comment by stefanscholz** [comment]
We're working on this, next version will be significantly better.

**Comment by stefanscholz** [comment]
Hi @abias,

in preparation of the official 1.3 release, could you please review if you are happy with the improvements we made?

Many thanks!
Stefan

**Comment by stefanscholz** [comment]
Fixed in 1.3
