### ISSUE TITLE
shortcodes and filtercodes

### ISSUE THREAD

**Issue by taymossimc** [bdecentgmbh/moodle-mod_pulse#18]
Question, is there either a way to get the filtercodes to work in the email message editing tool OR to extend the shortcodes already provided by Pulse?

**Comment by stefanscholz** [comment]
Ho @taymossimc ,

We already thought about doing that actually. It would be brilliant to have the versatility of filtercodes within pulse notifications.

Currently, we're in the middle of working out what the next version of pulse will be. We'll make sure to consider this!

However, right now it is only possible to do either of that via development. Feel free to provide a pull request if you have the knowledge - we're also open for funding for features btw.

Best
Stefan

**Comment by taymossimc** [comment]
Stefan, is there an email  for me to contact you privately about maybe funding you to create a little bit of customization for me?

**Comment by stefanscholz** [comment]
Sure thing! Best way to contact us would be via our live chat. Either go to chat.bdecent.de or click the chat bubble on any of our we sites. Alternatively, info@bdecent.de is fine too 😊

Cheers
Stefan

**Comment by stefanscholz** [comment]
Hi @taymossimc ,

just fyi: We're adding experimental filter and filter codes support in the next release. "Experimental" because we cannot guarantee that all filters actually work as expected — that's pretty much impossible to test. But we'll provide a list of filters know to work. 

Closing this issue.

**Comment by taymossimc** [comment]
Great, thanks.
-Tay
________________________________
