### ISSUE TITLE
Completion when available not working

### ISSUE THREAD

**Issue by davefoord** [bdecentgmbh/moodle-mod_pulse#2]
Just testing this out, and I have ticked the box for 'Completion when available', in my test the student is correctly seeing the pulse I had added, based on the availability restrictions, but the pulse item itself is not showing as complete, even though the students can see it. Is this a bug?

**Comment by stefanscholz** [comment]
Hi Dave,

thanks for posting this issue. 
Can you please provide more details on your setup, and which moodle version you are using?

Thanks!
Stefan

**Comment by davefoord** [comment]
Firstly, I think this plugin looks excellent, so looking forward to working with it.

I have Moodle 3.9.10+ (Build: 20210917) and pulse v1.11

I have enabled the 'Completion when available' option

![Capture2](https://user-images.githubusercontent.com/28855774/144602086-63c98dd0-3d71-4113-9119-2db648a4a0d4.PNG)

There are some availability restrictions so it shows when students have completed the assignment above:

![Capture3](https://user-images.githubusercontent.com/28855774/144602221-73cf754f-62f9-4e1d-bc7a-4eea4460039e.PNG)

Here is the student screen - which shows the pulse (it is just the text saying 'well done' being visible, but it hasn't marked itself as complete.

![Capture](https://user-images.githubusercontent.com/28855774/144601911-d7f46460-af57-4dc0-8800-01e54cc40c95.PNG)

And it isn't showing up in activity report as complete.

**Comment by stefanscholz** [comment]
Thanks for the details! That all looks good and should work.

Is it possible that the course has not yet started? I.e. that the course start date is tomorrow?

That's a common issue when testing pulse (but should be fine for any real life course).

**Comment by davefoord** [comment]
Ah yes - what a fool I am, the course end date was in the past (didn't spot this when testing, as learner could still access the course!), it now works as expected, looking forward to getting this in action.

**Comment by stefanscholz** [comment]
Great! I was fooled by that a couple of time already, too. So don't feel bad 😊

Don't hesitate to contact me again if you need any help!

(And we'll add this to the documentation....)
