### ISSUE TITLE
Feature request: choosing the "From" identity

### ISSUE THREAD

**Issue by taymossimc** [bdecentgmbh/moodle-mod_pulse#23]
I understand that Pulse uses the Teacher role to determine whom to set as the "from" for the outgoing email. In the case of multiple teachers it appears to be doing this based on the first teacher by alphabetical order? I think it would be a nice improvement if this "from" field could be set in the pulse settings. Maybe it is limited to choosing just from those assigned with Teacher or Non-editing Teacher or Manager roles, or maybe it's less restrictive? Maybe there would be a BCC field, as well, so that all outgoing email pulses could be automatically forwarded. 

Thanks for considering it.
-Tay Moss
https://churchx.ca

**Comment by stefanscholz** [comment]
Hi @taymossimc ,

that's not exactly correct. We rely on a permission to determine the sender, see the docs:
https://github.com/bdecentgmbh/moodle-mod_pulse/wiki#invitation

In the next major version of Pulse Pro (2.0) which is currently under development, it will be possible to configure the sender, add CC and BCC recipients!

Best Stefan

**Comment by taymossimc** [comment]
Right, but when it says "Pulse will use the first user as the sender" (based on permissions). What determines who the "first" user with Qmod/pulse:sender" is? Is it alphabetical?

-Tay
________________________________

**Comment by taymossimc** [comment]
Dumb question: how do I access the mod/pulse:sender capability for individual user? When I try to access it via the permissions panel in the course,  I don't see it among the other Pulse permissions?

-Tay
________________________________
