### ISSUE TITLE
Handling multiple languages?

### ISSUE THREAD

**Issue by taymossimc** [bdecentgmbh/moodle-mod_pulse#25]
I'm comfortable using the multi-language filter plugins and activity-level-language-restriction plugins to manage multiple languages within a single course. However, I'm not sure if there is a method to do this with pulse? I assume the filtercodes won't work because there is no "page" as context at the time the filtercodes are executed. Perhaps there should be a filtercode implementation at the pulse-level that uses the user's language preference from their profile?

**Comment by stefanscholz** [comment]
Multi lang support in notifications implemented in Version 1.3
