### ISSUE TITLE
Fatal error when trying to use this plugin on IOMAD

### ISSUE THREAD

**Issue by abias** [bdecentgmbh/moodle-mod_pulse#6]
Hi Stefan,

trying to use this plugin on the IOMAD distribution (https://github.com/iomad/iomad), I ran into a fatal error during the installation:

`Fatal error: Cannot declare class EmailVars, because the name is already in use in /var/www/mod/pulse/lib/vars.php on line 28
`

This error is caused by the fact that there is a class called `EmailVars` on https://github.com/bdecentgmbh/moodle-mod_pulse/blob/main/lib/vars.php as well as https://github.com/iomad/iomad/blob/IOMAD_310_STABLE/local/email/lib/vars.php and none of them is namespaced.

Do you think that there is a possibility to add a namespace to the class in mod_pulse to avoid class name clashes?

Cheers,
Alex

**Comment by stefanscholz** [comment]
Hi Alex, 

sure, I can ask my developers to add a namespace in the next release. If it's urgent, feel free to create a pull request ;)

Cheers
Stefan

**Comment by stefanscholz** [comment]
This should be fixed now:
https://github.com/bdecentgmbh/moodle-mod_pulse/blob/dev/lib/vars.php#L28
Works for you @abias?

**Comment by abias** [comment]
Thank you, Stefan, for fixing this issue.
Unfortunately, we do not have any customer anymore who intends to use pulse on IOMAD. That's why I do not have the ressources to re-test it.

I would rely on your experience that this is fixed and would close it.
