### ISSUE TITLE
 Coding error detected, it must be fixed by a programmer: Invalid icon system requested '\core\output\icon_system_standard'

### ISSUE THREAD

**Issue by digitalclm** [bdecentgmbh/moodle-mod_pulse#9]
I have just installed the pulse plugin for moodle version 4.0.4 and when I try to add a pulse asset to a course I get this error and it does not add the asset. 
Any idea?

**Comment by stefanscholz** [comment]
We tried to reproduce this issue but were not successful — everything worked as expected. If the issue persists on your site, kindly re-open this issue and provide steps to reproduce it. Thanks!
